pfe_analyser:
    resource: "@PfeAnalyserBundle/Controller/"
    type:     annotation
    prefix:   /

pfe_g_api:
    resource: "@PfeGPlaceApiBundle/Controller"
    prefix:   /gplace

pfe_geonames:
    resource: "@PfeGeonamesApiBundle/Controller"
    prefix:   /geonames

pfe_data:
    resource: "@PfeProviderBundle/Controller"
    prefix:   /provider

