pfe_data:
    resource: "@PfeCoreBundle/Controller"
    prefix:   /core

pfe_free_geo_ip:
    resource: "@PfeFreeGeoIpBundle/Controller/"
    type:     annotation
    prefix:   /freegeoip

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /provider/doc

pfe_g_api:
    resource: "@PfeGPlaceApiBundle/Controller"
    prefix:   /gplace

pfe_geonames:
    resource: "@PfeGeonamesApiBundle/Controller"
    prefix:   /geonames

pfe_provider:
    resource: "@PfeProviderBundle/Controller"
    prefix:   /provider

pfe_analyser:
    resource: "@PfeAnalyserBundle/Controller/"
    type:     annotation
    prefix:   /
