<?php

namespace Pfe\Bundle\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LocalisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalisationRepository extends EntityRepository {

}
