<?php

namespace Pfe\Bundle\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParticipantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantRepository extends EntityRepository {

    public function findAllLocalisations() {
        $dql = 'SELECT DISTINCT p.state, p.city, COUNT(p) as n FROM PfeCoreBundle:Participant as p GROUP BY p.state, p.city ORDER BY n, p.state, p.city';

        return $this->getEntityManager()->createQuery($dql)->getResult();
    }

    public function findAllStates() {
        $dql = 'SELECT DISTINCT p.state, COUNT(p) as n FROM PfeCoreBundle:Participant as p GROUP BY p.state ORDER BY n, p.state';

        return $this->getEntityManager()->createQuery($dql)->getResult();
    }

}
